{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0330b0ab-0b3b-4b5b-b613-759da01db00c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sqlite3\n",
    "import pandas as pd\n",
    "import logging\n",
    "from ingest_db import ingest_db\n",
    "\n",
    "logging.basicConfig(\n",
    "    filename = \"logs/get_vendor_summary.log\",\n",
    "    level = logging.DEBUG,\n",
    "    format = \"%(asctime)s - %(levelname)s - %(message)s\",\n",
    "    filemode = \"a\"\n",
    ")\n",
    "\n",
    "def create_vendor_summary(conn):\n",
    "    '''This function will merge the different tables to get the overall summary and add new columns to the resulting data'''\n",
    "    vendor_sales_summary = pd.read_sql_query(\"\"\"WITH FreightSummary AS (\n",
    "    SELECT \n",
    "        VendorNumber,\n",
    "        SUM(Freight) AS FreightCost\n",
    "    FROM vendor_invoice\n",
    "    GROUP BY VendorNumber\n",
    "    ),\n",
    "    \n",
    "    PurchaseSummary AS (\n",
    "        SELECT\n",
    "            p.VendorNumber,\n",
    "            p.VendorName,\n",
    "            p.Brand,\n",
    "            p.Description,\n",
    "            p.PurchasePrice,\n",
    "            pp.Price AS ActualPrice,\n",
    "            pp.Volume,\n",
    "            SUM(p.Quantity) AS TotalPurchaseQuantity,\n",
    "            SUM(p.Dollars) as TotalPurchaseDollars\n",
    "        FROM purchases p\n",
    "        JOIN purchase_prices pp\n",
    "            ON p.Brand = pp.Brand\n",
    "        WHERE p.PurchasePrice > 0\n",
    "        GROUP BY p.VendorNumber, p.VendorName, p.Brand, p.Description, p.PurchasePrice, pp.Price, pp.Volume\n",
    "    ),\n",
    "    \n",
    "    SalesSummary AS (\n",
    "        SELECT\n",
    "            VendorNo,\n",
    "            Brand,\n",
    "            SUM(SalesQuantity) as TotalSalesQuantity,\n",
    "            SUM(SalesDollars) as TotalSalesDollars,\n",
    "            SUM(SalesPrice) as TotalSalesPrice,\n",
    "            SUM(ExciseTax) as TotalExciseTax\n",
    "        FROM sales\n",
    "        GROUP BY VendorNo, Brand\n",
    "    )\n",
    "\n",
    "    SELECT\n",
    "        ps.VendorNumber,\n",
    "        ps.VendorName,\n",
    "        ps.Brand,\n",
    "        ps.Description,\n",
    "        ps.PurchasePrice,\n",
    "        ps.ActualPrice,\n",
    "        ps.Volume,\n",
    "        ps.TotalPurchaseQuantity,\n",
    "        ps.TotalPurchaseDollars,\n",
    "        ss.TotalSalesQuantity,\n",
    "        ss.TotalSalesDollars,\n",
    "        ss.TotalSalesPrice,\n",
    "        ss.TotalExciseTax,\n",
    "        fs.FreightCost\n",
    "    FROM PurchaseSummary ps\n",
    "    LEFT JOIN SalesSummary ss\n",
    "        ON ps.VendorNumber = ss.VendorNo\n",
    "        AND ps.Brand = ss.Brand\n",
    "    LEFT JOIN FreightSummary fs\n",
    "        ON ps.VendorNumber = fs.VendorNumber\n",
    "    ORDER BY ps.TotalPurchaseDollars DESC\"\"\", conn)\n",
    "    return vendor_sales_summary\n",
    "\n",
    "def clean_data(df):\n",
    "    '''This function cleans the data'''\n",
    "    # Convert volume to float64 data type\n",
    "    df['Volume'] = df['Volume'].astype('float64')\n",
    "    \n",
    "    # Fill in missing values with 0\n",
    "    df.fillna(0, inplace=True)\n",
    "    \n",
    "    # Strip whitespace from vendor names\n",
    "    df['VendorName'] = df['VendorName'].str.strip()\n",
    "    df['Description'] = df['Description'].str.strip()\n",
    "\n",
    "    # Create new columns\n",
    "    vendor_sales_summary['GrossProfit'] = vendor_sales_summary['TotalSalesDollars'] - vendor_sales_summary['TotalPurchaseDollars']\n",
    "    vendor_sales_summary['ProfitMargin'] = (vendor_sales_summary['GrossProfit'] / vendor_sales_summary['TotalSalesDollars']) * 100\n",
    "    vendor_sales_summary['StockTurnover'] = vendor_sales_summary['TotalSalesQuantity'] / vendor_sales_summary['TotalPurchaseQuantity']\n",
    "    vendor_sales_summary['SalestoPurchaseRatio'] = vendor_sales_summary['TotalSalesDollars'] / vendor_sales_summary['TotalPurchaseDollars']\n",
    "    \n",
    "    return df\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    # Create database connection\n",
    "    conn = sqlite3.connect('inventory.db')\n",
    "\n",
    "    logging.info('Creating Vendor Summary Table......')\n",
    "    summary_df = create_vendor_summary(conn)\n",
    "    logging.info(summary_df.head())\n",
    "\n",
    "    logging.info('Cleaning Data.........')\n",
    "    clean_df = clean_data(summary_df)\n",
    "    logging.info(clean_df.head())\n",
    "\n",
    "    logging.info('Ingesting Data........')\n",
    "    ingest_db(clean_df, 'vendor_sales_summary', conn)\n",
    "    logging.info('Completed')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1"
  },
  "widgets": {
   "application/vnd.jupyter.widget-state+json": {
    "state": {},
    "version_major": 2,
    "version_minor": 0
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
